# Generated by Django 4.1.5 on 2023-01-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='password',
            name='password_for_the_service',
            field=models.TextField(verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='password',
            name='service',
            field=models.TextField(verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='password',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Заголовок'),
        ),
    ]
